### ISSUE TITLE
Command line tool

### ISSUE THREAD

**Issue by ChrisChinchilla** [feedreader/jekyll-planet#1]
Hi,

I'm not sure if you're still maintaining this. I have one small problem, but it's stopping me even getting started. I install the gem, but the command line tool mentioned isn't available.

Any ideas and thanks :)

**Comment by geraldb** [comment]
Thanks for your interest. Please post questions to the [wwwmake forum](http://groups.google.com/group/wwwmake). Thanks. The issue here are just for bugs. Sorry.

**Comment by ChrisChinchilla** [comment]
Sure…

It didn't work after following instructions, so I thought it was a bug, sorry!

**Comment by geraldb** [comment]
Sorry I know it's forever past but just for new readers - `planet.rb` is now a single-file script (and "un-gemified") - just use `ruby ./planet.rb` to run on your own computer.
