### ISSUE TITLE
Not Getting Original_Link

### ISSUE THREAD

**Issue by oakeef** [feedreader/jekyll-planet#3]
when running `ruby -r 'jekyll/planet' -e 'JekyllPlanet.main'` None of my posts have original_link in the frontmatter. There is definitely a `<link>` in the content as well

**Comment by geraldb** [comment]
The planet tool is a one-file script, see <https://github.com/feedreader/planet.rb/blob/master/planet.rb#L78> for outputting the original_link.   All the feed reader "machinery" is in the pluto gem / library that stores everything in a single-file SQLite database.   You can check the sqlite database e.g. planet.db to see if the item url is present.

**Comment by oakeef** [comment]
@geraldb it appears to be present in the planet.db I guess I should probably dive into the source code

**Comment by geraldb** [comment]
That's weird than it should get outputted. Sorry.  As far as I can remember you can "just" copy the planet.rb  script  and you should be able to run and test it easily e.g. `ruby ./planet.rb` should work. Good luck. Greetings from Vienna. Cheers.

**Comment by geraldb** [comment]
Sorry I know it's forever past but just for new readers - `planet.rb` is now a single-file script (and "un-gemified") - just use `ruby ./planet.rb` to run on your own computer.
